#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

beginswith() { case $2 in "$1"*) true ;; *) false ;; esac }

push_command=$(ps -ocommand= -p $PPID | cut -d' ' -f 4)
protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

is_push_to_main_origin=$(beginswith git@github.com:/fingerprintjs/ "$push_command")

# Block pushes only to protected branch in main repository
if $is_push_to_main_origin && [ "$protected_branch" = "$current_branch" ]; then
  echo "You are on the $protected_branch branch, push blocked."
  exit 1 # push will not execute
fi
